---
name: Probe-MachineInfo
version: 0.11
author:
  - 'Sagar R. Shah <sagarshah@softhome.net>'
abstract: The great new Probe::MachineInfo!
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Linux::Distribution: 0.11
  POSIX: 0
  Proc::Reliable: 0
  Test::More: 0
  Unix::Processors: 0
provides:
  Probe::MachineInfo:
    file: lib/Probe/MachineInfo.pm
    version: 0.11
  Probe::MachineInfo::ClockSpeed:
    file: lib/Probe/MachineInfo/ClockSpeed.pm
  Probe::MachineInfo::Distribution:
    file: lib/Probe/MachineInfo/Distribution.pm
  Probe::MachineInfo::Hostid:
    file: lib/Probe/MachineInfo/Hostid.pm
  Probe::MachineInfo::Hostname:
    file: lib/Probe/MachineInfo/Hostname.pm
  Probe::MachineInfo::IpAddress:
    file: lib/Probe/MachineInfo/IpAddress.pm
  Probe::MachineInfo::KeepAlive:
    file: lib/Probe/MachineInfo/KeepAlive.pm
  Probe::MachineInfo::Metric:
    file: lib/Probe/MachineInfo/Metric.pm
  Probe::MachineInfo::NumCPUs:
    file: lib/Probe/MachineInfo/NumCPUs.pm
  Probe::MachineInfo::OS:
    file: lib/Probe/MachineInfo/OS.pm
  Probe::MachineInfo::SimpleMetric:
    file: lib/Probe/MachineInfo/SimpleMetric.pm
  Probe::MachineInfo::Uptime:
    file: lib/Probe/MachineInfo/Uptime.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
